### ISSUE TITLE
Command doesn't work on Django 1.8

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-invitations#18]
$ ./manage.py add_invites 10
    usage: manage.py add_invites [-h] [--version] [-v {0,1,2,3}]
                             [--settings SETTINGS] [--pythonpath PYTHONPATH]
                             [--traceback] [--no-color]
    manage.py add_invites: error: unrecognized arguments: 10

**Comment by grahamu** [comment]
This issue stems from a backwards incompatible change in v1.8: https://docs.djangoproject.com/en/1.9/releases/1.8/#management-commands-that-only-accept-positional-arguments.

In order to support Django < 1.8 we can simply add an `args` attribute to the Command.

I believe this affects all three pinax-invitations management commands.
